top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/modules/mappers
builddir     = /tmp/sos/httpd-2.2.32/modules/mappers
VPATH        = /tmp/sos/httpd-2.2.32/modules/mappers

include $(top_srcdir)/build/special.mk

