top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/modules/metadata
builddir     = /tmp/sos/httpd-2.2.32/modules/metadata
VPATH        = /tmp/sos/httpd-2.2.32/modules/metadata

include $(top_srcdir)/build/special.mk

