top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/modules/loggers
builddir     = /tmp/sos/httpd-2.2.32/modules/loggers
VPATH        = /tmp/sos/httpd-2.2.32/modules/loggers

include $(top_srcdir)/build/special.mk

