top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/modules/generators
builddir     = /tmp/sos/httpd-2.2.32/modules/generators
VPATH        = /tmp/sos/httpd-2.2.32/modules/generators

include $(top_srcdir)/build/special.mk

