top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/server/mpm/prefork
builddir     = /tmp/sos/httpd-2.2.32/server/mpm/prefork
VPATH        = /tmp/sos/httpd-2.2.32/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
