top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/server/mpm/itk
builddir     = /tmp/sos/httpd-2.2.32/server/mpm/itk
VPATH        = /tmp/sos/httpd-2.2.32/server/mpm/itk
