top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/modules/echo
builddir     = /tmp/sos/httpd-2.2.32/modules/echo
VPATH        = /tmp/sos/httpd-2.2.32/modules/echo

include $(top_srcdir)/build/special.mk

