top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/server/mpm/experimental/event
builddir     = /tmp/sos/httpd-2.2.32/server/mpm/experimental/event
VPATH        = /tmp/sos/httpd-2.2.32/server/mpm/experimental/event

LTLIBRARY_NAME    = libevent.la
LTLIBRARY_SOURCES = event.c fdqueue.c pod.c

include $(top_srcdir)/build/ltlib.mk
