top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/modules/filters
builddir     = /tmp/sos/httpd-2.2.32/modules/filters
VPATH        = /tmp/sos/httpd-2.2.32/modules/filters

include $(top_srcdir)/build/special.mk

