top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/modules/aaa
builddir     = /tmp/sos/httpd-2.2.32/modules/aaa
VPATH        = /tmp/sos/httpd-2.2.32/modules/aaa

include $(top_srcdir)/build/special.mk

