top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/modules/cache
builddir     = /tmp/sos/httpd-2.2.32/modules/cache
VPATH        = /tmp/sos/httpd-2.2.32/modules/cache

include $(top_srcdir)/build/special.mk

