top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/os
builddir     = /tmp/sos/httpd-2.2.32/os
VPATH        = /tmp/sos/httpd-2.2.32/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
