top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/server/mpm/experimental/itk
builddir     = /tmp/sos/httpd-2.2.32/server/mpm/experimental/itk
VPATH        = /tmp/sos/httpd-2.2.32/server/mpm/experimental/itk

LTLIBRARY_NAME    = libitk.la
LTLIBRARY_SOURCES = itk.c

include $(top_srcdir)/build/ltlib.mk
