top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/modules/dav/lock
builddir     = /tmp/sos/httpd-2.2.32/modules/dav/lock
VPATH        = /tmp/sos/httpd-2.2.32/modules/dav/lock
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
