top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/modules/http
builddir     = /tmp/sos/httpd-2.2.32/modules/http
VPATH        = /tmp/sos/httpd-2.2.32/modules/http

include $(top_srcdir)/build/special.mk

