top_srcdir   = /tmp/sos/httpd-2.2.32
top_builddir = /tmp/sos/httpd-2.2.32
srcdir       = /tmp/sos/httpd-2.2.32/server/mpm
builddir     = /tmp/sos/httpd-2.2.32/server/mpm
VPATH        = /tmp/sos/httpd-2.2.32/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
